---
# file: tasks/apparmor.yml
#
# apparmor configuration tasks.
#

- name: apparmor | ensure cache directory is present in the apparmor configuration
  lineinfile:
    dest=/etc/apparmor.d/usr.sbin.named
    line="  {{ item }},"
    insertbefore='}'
  with_items:
    - "{{ bind_dir_cache }}/** lrw"
    - "{{ bind_dir_cache }}/ rw"

- name: apparmor | ensure log directory is present in the apparmor configuration
  lineinfile:
    dest=/etc/apparmor.d/usr.sbin.named
    line="  {{ item }} rw,"
    insertbefore='}'
  with_items:
    - "{{ bind_dir_log }}/**"
    - "{{ bind_dir_log }}/"
