---
# file: tasks/configuration.yml
#
# configuration tasks.
#

- name: ensure integrity of /etc/default/bind9 file
  template:
    src=etc/default/bind9.j2
    dest=/etc/default/bind9
    owner=root
    group=root
    mode=0644
  notify: restart bind9

- name: ensure integrity of /etc/bind/named.conf.* files
  template:
    src="etc/bind/named.conf{{ item }}.j2"
    dest="/etc/bind/named.conf{{ item }}"
    owner=root
    group=root
    mode=0644
  with_items:
    - ''
    - '.acl'
    - '.controls'
    - '.keys'
    - '.local'
    - '.logging'
    - '.options'
  notify: restart bind9

- name: generate custom zone databases
  template:
    src=var/cache/bind/db.name.zone.j2
    dest="{{ bind_dir_cache }}/db.{{ item.key }}.zone"
    owner=bind
    group=bind
    mode=0644
  with_dict: "{{ bind_zone_databases }}"
